services:
  client:
    build: ./client
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/app

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  server:
    build: ./server
    entrypoint: sh -c "npm install && npm run dev"
    ports:
      - 5000:5000
    volumes:
      - ./server:/home/node/app
